#!/bin/sh
cd "${0%/*}" || exit 1


blockMesh > LOG.blockMesh
echo "Mesh is created!"
snappyHexMesh -overwrite > LOG.snappyMesh
echo "Mesh is snapped!"
checkMesh > LOG.checkMesh
echo "Mesh is checked!"
simpleFoam > LOG.simpleFoam
echo "Simulation is done!"
gnuplot plot.gnu
echo "PLotted!"

tail -500 postProcessing/forceCoeffs/0/coefficient.dat | awk '!/^#/ {sum += $2; n += 1} END {print "Mean Cd =", sum/n}'
echo "DONE!"
